title: Summer's Log
description: Research, writing, and things I'm thinking about.
author: Summer
url: "https://untitledlife.github.io"
baseurl: "/summerslog"

theme: minima

collections:
  presentations:
    output: true
    permalink: /presentations/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "default"

markdown: kramdown
